### PR TITLE
Define STFT output_format at instantiation

### PR DESCRIPTION
**Pull request by tasercake**
Possible fix for #52

The `output_format` parameter is defined first in the `__init__()` method, but there's still the option to override it when calling `forward()`

### CODE REVIEW

**Comment by KinWaiCheuk** [comment]
Hi tasercake, I have checked your fix with my unit tests, it does not affect other functionalities. (I updated my unit tests and fixed another problem, so you might want to pull the latest version before you continue)
But I think we need a better error message to catch the errors in the following scenario. For example:

```
import sys
sys.path.insert(0, '../Installation/nnAudio/')
import Spectrogram
from scipy.io import wavfile
import torch
import librosa

device = 'cuda:1'

example_y, example_sr = librosa.load(librosa.util.example_audio_file())

x = torch.tensor(example_y, device=device)[:44100]
# Get an STFT magnitude spectrogram
to_stft = Spectrogram.STFT(n_fft=256,device=device, output_format="Complex")
stft = to_stft(x, output_format="Magnitude")

# Reconstruct audio from STFT
reconstructed = to_stft.inverse(stft)
# Reconstruct audio from STFT (again)
reconstructed = to_stft.inverse(stft)
```
> AssertionError: Only perform inverse function on Magnitude or Complex spectrogram.

This error is not informative enough to tell the user what is wrong.

My suggestion is: when initializing with `STFT(output_format="Complex")` , we should remind the user that the `iSTFT` would be the inverse mode. Similarly, when initializing with `STFT(output_format="Magnitude")`, remind the user griffin-lim will be used as the inverse function.

If `iSTFT` is the inverse mode, but the user pass a magnitude tensor of the shape (batch, f_bins, timesteps) to the `.inverse` method, throw an error like "iSTFT takes in complex spectrograms as input, but the input seems like magnitude spectrograms now".

Similarly, if `Griffin-Lim` is the inverse mode, but the user pass a complex tensor of the shape (batch, f_bins, timesteps, 2) to the `.inverse` method, throw an error like this "Griffin-Lim takes in magnitude spectrograms as input, but the input seems like complex spectrograms now".

I think everything would be good to go after optimising the error catching. I forgot to revert the STFT code back to original one during my last git push, maybe you need to download the file again and work on the latest one.

**Comment by KinWaiCheuk** [comment]
I discover one more problem during further testing today.

```
example_y, example_sr = librosa.load(librosa.util.example_audio_file())

x = torch.tensor(example_y, device=device)[:44100]
# Get an STFT magnitude spectrogram
to_stft = Spectrogram.STFT(n_fft=256,device=device, output_format="Complex")
stft = to_stft(x)

# Reconstruct audio from STFT
reconstructed = to_stft.inverse(stft)
# Reconstruct audio from STFT (again)
reconstructed = to_stft.inverse(stft)
```

This code will give you the following error
> AttributeError: 'NoneType' object has no attribute 'shape'

The problem is the default setting for `.forward()` is `output_format=None`. Therefore, when the user dose not specific anything for `forward()`, it would be better that the default setting would be same as the `self.output_format`.  I am fixing another windowing problem for griffin-lim right now, will come back to this problem later.

**Review by KinWaiCheuk — APPROVED** [review]
The major errors are fix. But in the future, we might need to do a better error catching when the input format does not match with the the `.inverse` mode.

e.g. `.inverse` mode is in Griffin-Lim, but the input is a complex value spectrogram
or    `.inverse` mode is in ISTFT, but the input is a magnitude spectrogram

**Comment by tasercake** [comment]
Thanks, I'll take a look at the error checking problem soon.

I also just realised that my diff is a lot bigger than it needed to be due to the difference in line endings (I made my commits on Windows). It might be a good idea to change them back to the UNIX convention, but I haven't dealt with that issue before.

**Comment by KinWaiCheuk** [comment]
So far I don't see any noticeable difference in the `Spectrogram.py`. But I will bear this in mind in case problems appear in the future.

I haven't dealt with differences in line endings either, so I am also not sure what would the impact be.

**Pull request merged**
